name: Trigger Firebase Deploy

on:
  push:
    branches: [main]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger reefos-firestore-functions deploy
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/CoralGardeners/reefos-firestore-functions/dispatches \
            -d '{"event_type": "dependency-updated", "client_payload": {"repo": "reefos-data-api", "sha": "${{ github.sha }}"}}'
